import type { Metadata } from "next";
import SideBar from "@components/SideBar"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       <main className="flex h-screen w-full font-inter">
      <SideBar/>
       {children}
       </main>
      </body>
    </html>
  );
}
